// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ENTER_MAP_C2S : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ENTER_MAP_C2S GetRootAsENTER_MAP_C2S(ByteBuffer _bb) { return GetRootAsENTER_MAP_C2S(_bb, new ENTER_MAP_C2S()); }
  public static ENTER_MAP_C2S GetRootAsENTER_MAP_C2S(ByteBuffer _bb, ENTER_MAP_C2S obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ENTER_MAP_C2S __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<protocol.ENTER_MAP_C2S> CreateENTER_MAP_C2S(FlatBufferBuilder builder,
      uint map_id = 0) {
    builder.StartTable(1);
    ENTER_MAP_C2S.AddMapId(builder, map_id);
    return ENTER_MAP_C2S.EndENTER_MAP_C2S(builder);
  }

  public static void StartENTER_MAP_C2S(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMapId(FlatBufferBuilder builder, uint mapId) { builder.AddUint(0, mapId, 0); }
  public static Offset<protocol.ENTER_MAP_C2S> EndENTER_MAP_C2S(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.ENTER_MAP_C2S>(o);
  }
};


}
