// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ENTITY_DESTROY_S2C : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ENTITY_DESTROY_S2C GetRootAsENTITY_DESTROY_S2C(ByteBuffer _bb) { return GetRootAsENTITY_DESTROY_S2C(_bb, new ENTITY_DESTROY_S2C()); }
  public static ENTITY_DESTROY_S2C GetRootAsENTITY_DESTROY_S2C(ByteBuffer _bb, ENTITY_DESTROY_S2C obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ENTITY_DESTROY_S2C __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.ENTITY_DESTROY_S2C> CreateENTITY_DESTROY_S2C(FlatBufferBuilder builder,
      ulong uid = 0) {
    builder.StartTable(1);
    ENTITY_DESTROY_S2C.AddUid(builder, uid);
    return ENTITY_DESTROY_S2C.EndENTITY_DESTROY_S2C(builder);
  }

  public static void StartENTITY_DESTROY_S2C(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUid(FlatBufferBuilder builder, ulong uid) { builder.AddUlong(0, uid, 0); }
  public static Offset<protocol.ENTITY_DESTROY_S2C> EndENTITY_DESTROY_S2C(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.ENTITY_DESTROY_S2C>(o);
  }
};


}
