// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ENTITY_MOVE_STOP_S2C : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ENTITY_MOVE_STOP_S2C GetRootAsENTITY_MOVE_STOP_S2C(ByteBuffer _bb) { return GetRootAsENTITY_MOVE_STOP_S2C(_bb, new ENTITY_MOVE_STOP_S2C()); }
  public static ENTITY_MOVE_STOP_S2C GetRootAsENTITY_MOVE_STOP_S2C(ByteBuffer _bb, ENTITY_MOVE_STOP_S2C obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ENTITY_MOVE_STOP_S2C __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public common.RESULT_CODE Result { get { int o = __p.__offset(4); return o != 0 ? (common.RESULT_CODE)__p.bb.GetUint(o + __p.bb_pos) : common.RESULT_CODE.ERROR_FAIL; } }
  public ulong Uid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong ExcuteTime { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public common.VECTOR3? Position { get { int o = __p.__offset(10); return o != 0 ? (common.VECTOR3?)(new common.VECTOR3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ulong ServerTime { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static void StartENTITY_MOVE_STOP_S2C(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddResult(FlatBufferBuilder builder, common.RESULT_CODE result) { builder.AddUint(0, (uint)result, 0); }
  public static void AddUid(FlatBufferBuilder builder, ulong uid) { builder.AddUlong(1, uid, 0); }
  public static void AddExcuteTime(FlatBufferBuilder builder, ulong excuteTime) { builder.AddUlong(2, excuteTime, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<common.VECTOR3> positionOffset) { builder.AddStruct(3, positionOffset.Value, 0); }
  public static void AddServerTime(FlatBufferBuilder builder, ulong serverTime) { builder.AddUlong(4, serverTime, 0); }
  public static Offset<protocol.ENTITY_MOVE_STOP_S2C> EndENTITY_MOVE_STOP_S2C(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.ENTITY_MOVE_STOP_S2C>(o);
  }
};


}
