// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct HEART_BEAT_S2C : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static HEART_BEAT_S2C GetRootAsHEART_BEAT_S2C(ByteBuffer _bb) { return GetRootAsHEART_BEAT_S2C(_bb, new HEART_BEAT_S2C()); }
  public static HEART_BEAT_S2C GetRootAsHEART_BEAT_S2C(ByteBuffer _bb, HEART_BEAT_S2C obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HEART_BEAT_S2C __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartHEART_BEAT_S2C(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<protocol.HEART_BEAT_S2C> EndHEART_BEAT_S2C(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.HEART_BEAT_S2C>(o);
  }
};


}
